mbta/on_prem_deploy

.github/workflows/build_docker_images.yaml
build_elixir_container.ps1
build_erlang_container.ps1
docker/.dockerignore
docker/Dockerfile.elixir
docker/Dockerfile.erlang

Unfortunately, Hex.pm does not create builds for Windows. And without Docker builds for Windows, each time one of our Windows applications would want to build an Erlang/Elixir application, they would need to do it themselves.
This action creates a set of builds for a given set of Erlang/Elixir versions. From there, Docker containers for individual applications can use them as they would for Linux containers: using them as the base for building a release.
Currently these are going into my personal DockerHub (https://hub.docker.com/repository/docker/paulswartz/windows-erlang/tags and https://hub.docker.com/repository/docker/paulswartz/windows-elixir/tags) but we should update that to go into the `mbta` account as a part of merging this.

feat: GitHub Actions to build Erlang/Elixir for Windows

---

.github/workflows/build_docker_images.yaml
docker/Dockerfile.elixir
docker/Dockerfile.erlang

This will allow us to build containers with the existing versions of Erlang/Elixir, rather than needing to update before we migrate to a container.

include more versions of Erlang/Elixir in the build matrix

---

.github/workflows/build_docker_images.yaml
.github/workflows/ci.yml
docker/Dockerfile.erlang

Otherwise, multiple jobs will try to build the same Erlang container.

include new Erlang versions, build them before the Elixir containers

---

linux/inventory.yml
linux/main.yml
linux/roles/ecs_anywhere/defaults/main.yml
linux/roles/ecs_anywhere/tasks/main.yml
linux/roles/onprem/tasks/ansible-pull.yml

The SSM tag is useful because it shows the hostname in the SSM console.
The ECS tags are useful because we can limit tasks to particular instances (see mbta/devops#1004)

feat: register SSM/ECS tags for instances

---

linux/roles/onprem/tasks/ansible-pull.yml
linux/roles/onprem/tasks/main.yml
linux/roles/onprem/tasks/needs-restart.yml

From here, we can create an alert which will notify us when the server (or relevant services) need to be restarted.
---
- https://app.asana.com/0/0/1204918040375937

feat: log `needrestart` output to Splunk every day

---

linux/roles/onprem/tasks/ansible-pull.yml

Otherwise, we download 4M of Ansible packages every hour.

fix: only install Ansible requirements when they change

---

linux/roles/ecs_anywhere/tasks/main.yml
linux/roles/metrics/tasks/main.yml
linux/roles/onprem/tasks/ansible-pull.yml
linux/roles/onprem/tasks/needs-restart.yml
linux/roles/splunk/tasks/main.yml

- only update the cache if the relevant repo was added
- pass list to `name` rather than looping
- only unzip Splunk configuration once

more efficiency updates

---

linux/roles/ecs_anywhere/tasks/main.yml

This is the path that the ECS Anywhere install script checks to see if the install has already happened. For some reason, `/etc/init/amazon-ssm-agent.conf` is not always created.

fix: change path for detecting ECS Anywhere

---

linux/roles/onprem/tasks/ansible-pull.yml

This avoids needing to re-update the cache when installing cron/Ansible.
Asana: https://app.asana.com/0/1113545750913664/1205309479399573/f

fix: update the cache as a part of installing the PPA

---

.github/workflows/deploy_document.yml

This PR updates the deploy workflow to use v2 of the shared `build-push-ecr` and `deploy-ecs` actions. These updated actions assume an IAM role instead of relying on long-lasting AWS keys for an IAM user

Chore: Update GitHub actions to use assumed role

---

.github/workflows/vagrant-up.yml

The "vagrant-up" CI check hasn't been working for a while. I investigated and found [this GitHub issue](https://github.com/actions/runner-images/issues/8730) that implies the issue lies with the macOS runner, and persists despite some attempts to fix it.
Let's set this check to only run manually for now, and test changes locally as needed.

fix: disable failing Vagrant CI check

---

linux/group_vars/local/service_registration.yml
linux/roles/crowdstrike/defaults/main.yml
linux/roles/crowdstrike/tasks/main.yml
linux/roles/ecs_anywhere/defaults/main.yml
linux/roles/ecs_anywhere/tasks/install-ecs-agent.yml
linux/roles/ecs_anywhere/tasks/main.yml
linux/roles/splunk/defaults/main.yml
linux/roles/splunk/tasks/main.yml
linux/roles/tenable/defaults/main.yml
linux/roles/tenable/tasks/main.yml

Some roles (CrowdStrike, ECS Anywhere, Splunk, Tenable) contain tasks that register or call out to other systems. These can make testing of the overall Ansible configuration difficult, so it's useful to have the option to disable those callouts when testing.

feat: Add role vars to optionally disable certain tasks

---

linux/build_ova.sh
linux/group_vars/splunk_base_image/users.yml
linux/inventory.yml
linux/main.yml

Tested in QEMU and confirmed that it provisions successfully.
@rkuthuru12 to build images:
1. Clone this repo
2. If this PR isn't merged yet, switch to `idw-splunk-hf` branch
3. Run:
```bash
cd linux/
bash ./build_ova.sh <hostname> <ip_address>
```
4. Repeat step 3 for each server image
5. Share `tmp/<hostname>.ova` files with infrastructure team for provisioning
---
- https://app.asana.com/0/0/1206851728384043

feat: Support provisioning base images for Splunk servers

---

linux/group_vars/arrival_screen/users.yml

This should allow team members to ssh into the bus shelter screens (and any future screens that use this Ansible setup) when necessary.

chore: Add digital ride team engineers to arrival screen users

---

linux/roles/ecs_anywhere/tasks/install-docker.yml

I ran into an issue with this when configuring HSCTDLNXSTG02, where it complained that docker-ce wasn't installed first.

fix: remove unused dpkg task

---

linux/group_vars/staging/users.yml

Adding Warren Johnson user "wjohnson" to Linux on prem servers.  Public key pulled from https://github.com/Warren-Johnson-TID

Add wjohnson user to linux on prem

---

linux/roles/splunk/defaults/main.yml
linux/roles/splunk/tasks/install-splunk.yml

Try as we might, we cannot get 9.3.0 to work properly.  It simply won't listen at the requested port and therefore is not sending information (cpu, memory etc) metrics back to Splunk.

Revert Splunk Universal Forwared from 9.3.0 to 9.0.4

---

linux/roles/splunk/tasks/install-splunk.yml

on_prem linux staging doesn't seem to be able to downgrade the Splunk Universal Forwarder from 9.3.0 to 9.0.4.  Adding "allow_downgrade: yes" to the Spunk Installer should fix that

Allow apt on linux staging to downgrade package versions

---

linux/roles/docker/tasks/main.yml

@ianwestcott [commented](https://github.com/mbta/on_prem_deploy/pull/71#issuecomment-2334278576) in #71 that I need to add an `include_tasks` block for this to run automatically. I referred to the [Ansible docs](https://docs.ansible.com/ansible/5/collections/ansible/builtin/include_tasks_module.html#ansible-collections-ansible-builtin-include-tasks-module) here; happy to adjust as needed but I didn't include any tags or conditions.

Fix: Include Prune Task in main.yml

---

linux/roles/scu/templates/run-scully.j2

This calls a setup task to switch the SCU audio card to mono mode, before running the app. This needs to be handled separately, because switching modes requires a hardware reset on the audio card, which is a privileged operation.

set SCU audio mode on app startup

---

linux/build_scu_iso
linux/build_user_data.sh
linux/group_vars/scu/users.yml
linux/roles/scu/tasks/main.yml
linux/scu/autoinstall.yaml

Fixes a few issues that came up during testing of the SCU install process.
* Makes the ISO build script fail loudly on errors
* Allows specifying git branches with slashes
* Adds users to the `admin` group for sudo privileges
* Uses the `classic` flag to install the SSM agent
* Installs the SSH server on SCUs
---
- https://app.asana.com/0/0/1208422519448697

fix SCU installation scripts

---

linux/group_vars/scu/users.yml
linux/roles/docker/tasks/main.yml

This adds the other screens team members as SCU users so they can log in as well. Adds all users to the `docker` group.
Also changes the docker installation steps to use a more standard pattern for adding the apt repo. I saw an intermittent failure on this step, where the package wasn't found, and it seemed like a timing issue around updating apt after adding the repo. Using the `apt_repository` builtin should behave better and handle the update automatically.
---
- https://app.asana.com/0/0/1208568231374247

add screens team users and fix docker installation

---

linux/roles/scu/templates/run-scully.j2

This fixes the port mapping for the Scully container. The service will run on port 4010 internally, so we map to that.
---
- https://app.asana.com/0/0/1208600087427249

fix scully port mapping

---

linux/roles/scu/templates/run-scully.j2

This reads the Splunk token from secrets manager and passes it via the environment to the Scully container.

pass splunk token in Scully environment

---

linux/roles/scu/templates/run-scully.j2

[Allow internal users to send a test message to Linux SCU](https://app.asana.com/0/1185117109217413/1208799900937739/f)
This reads the recently-added secret value and passes it via environment variable to the scully container.

inject SECRET_KEY_BASE for scully

---

linux/scu/autoinstall.yaml

This explicitly specifies the apt sources list for SCU images, in order to force the use of HTTPS. This is necessary because the PA network blocks HTTP traffic.

force https for apt update

---

linux/cloud-init/user-data
linux/inventory.yml
linux/roles/ansible/tasks/main.yml

This PR makes two changes to Linux on-prem config:
- Updates the SSH key for CloudInit to use a credential not connected to a single user
- Adds flexibility to accept Markley Lowell hostname conventions

chore: update SSH key and prod hostnames

---

.gitignore

Just in case it gets added to the wrong path.

fix: exclude .ansible_vault_password everywhere

---

linux/group_vars/all/users.yml
linux/group_vars/staging/users.yml

This PR removes users who have left TID from the configuration.

chore: remove WDJ user from staging group

---

.github/workflows/ci.yml
.github/workflows/vagrant-up.yml
.gitignore
.rtx.toml
.tool-versions
.yamllint.yml
linux/README.md
pyproject.toml
requirements.txt
uv.lock

The existing dev setup had an undocumented dependency on a "global" Python 3.10+ installation (macOS ships with 3.9), due to a quirk of `asdf-pyapp`. The main idea of this change is to remove that plugin in favor of using Ansible as an ordinary Python package, within a project-local Python environment. [`uv`](https://docs.astral.sh/uv/) is used as a one-stop environment/package manager.
Some positive effects of this change:
* makes the project's Python dependencies "visible" to Renovate ([but probably not Dependabot](https://github.com/dependabot/dependabot-core/issues/10478)), should we want to enable it for this repo
* locks dependency versions, guarding against supply-chain attacks on developer machines or the CI environment
* simplifies the CI workflow and aligns it better with local …

dev: improve tool/dependency management

---

linux/group_vars/all/users.yml

Companion to https://github.com/mbta/devops/pull/3165 to keep user list in sync while Ansible configuration is migrated

chore: add crunkel to TID Engineers

---

linux/inventory.yml

This PR removes the PPCTDLNXPRD server from our inventory. It does the same for never-used PPCTDLNXSTG, as all Park Plaza datacenters have migrated (or will soon migrate) to Markley Lowell. 
I didn't touch the Splunk items in inventory because I wasn't sure of the InfoSec plan for migrating/decommissioning these servers. 
---
- https://app.asana.com/0/0/1210811468864162

chore: remove PPCTDLNXPRD and STG from inventory
